version: "3.9"

services:
  # ==========================
  # PostgreSQL Database
  # ==========================
  postgres:
    image: postgres:15-alpine
    container_name: taskmanager_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-taskdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - taskmanager_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-taskdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ==========================
  # Go API Application
  # ==========================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskmanager:latest
    container_name: taskmanager_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-taskdb}
      DB_PORT: 5432
      SERVER_PORT: ${SERVER_PORT:-1212}
      BASE_URL: ${BASE_URL:-http://localhost:1212}
      GIN_MODE: release
      TZ: Asia/Tashkent
    ports:
      - "${SERVER_PORT:-1212}:1212"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - taskmanager_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ==========================
  # pgAdmin (Optional)
  # ==========================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: taskmanager_pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - taskmanager_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ==========================
# VOLUMES & NETWORKS
# ==========================
volumes:
  postgres_data:
  pgadmin_data:

networks:
  taskmanager_network:
    driver: bridge
