version: '3.8'

services:
  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-api
    ports:
      - "1212:1212"
    volumes:
      - ./uploads:/root/uploads
      - ./database.json:/root/database.json
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    networks:
      - taskmanager-network

networks:
  taskmanager-network:
    driver: bridge