version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: taskmanager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taskmanager_network

  # Task Manager API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager_api
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: taskdb
      DB_PORT: 5432
      API_PORT: 1212
      GIN_MODE: release
    ports:
      - "127.0.0.1:1212:1212"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./docs:/app/docs
    networks:
      - taskmanager_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  taskmanager_network:
    driver: bridge