
services:
  taskmanager-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-api
    ports:
      - "1212:1212"
    volumes:
      - ./uploads:/app/uploads
      - ./data/database.json:/app/data/database.json
    environment:
      - TZ=Asia/Tashkent
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:1212/categories"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s